### ISSUE TITLE
TPU dies after 3hrs, no error promoted to client code

### ISSUE THREAD

**Issue by pwais** [tensorflow/tpu#609]
Continued from https://github.com/tensorflow/tpu/issues/590 , which was closed citing an irrelevant patch.

Training using RetinaNet and/or a very similar training flow.  Like clockwork, 3hrs of training and then I start seeing health UNKNOWN and the client spins indefinitely. Nothing significant in stackdriver logs.

![Screen Shot 2019-11-13 at 01 09 31](https://user-images.githubusercontent.com/218145/69217775-3be7da00-0b24-11ea-9f7b-7310010d8722.png)

**Comment by ChristopherBrix** [comment]
I have the same problem. However, it is does not die after 3 hours, it dies at a random point in time. Sometimes it will run for multiple hours, just now it died within 30 minutes.

```
INFO:tensorflow:examples/sec: 1054.45
I1120 13:39:32.849041 140684764419520 tpu_estimator.py:2308] examples/sec: 1054.45
INFO:tensorflow:Enqueue next (1000) batch(es) of data to infeed.
I1120 13:39:32.850109 140684764419520 tpu_estimator.py:600] Enqueue next (1000) batch(es) of data to infeed.
INFO:tensorflow:Dequeue next (1000) batch(es) of data from outfeed.
I1120 13:39:32.850718 140684764419520 tpu_estimator.py:604] Dequeue next (1000) batch(es) of data from outfeed.
INFO:tensorflow:Outfeed finished for iteration (6, 4)
I1120 13:39:33.536053 140681504278272 tpu_estimator.py:279] Outfeed finished for iteration (6, 4)
I1120 13:39:39.742182 140681495885568 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
W1120 13:39:39.796293 140681495885568 preempted_hook.py:91] TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
I1120 13:40:09.865722 140681495885568 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
W1120 13:40:09.922341 140681495885568 preempted_hook.py:91] TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
INFO:tensorflow:loss = 1.70311, step = 57000 (60.980 sec)
I1120 13:40:33.826905 140684764419520 basic_session_run_hooks.py:260] loss = 1.70311, step = 57000 (60.980 sec)
INFO:tensorflow:global_step/sec: 16.3988
I1120 13:40:33.828651 140684764419520 tpu_estimator.py:2307] global_step/sec: 16.3988
INFO:tensorflow:examples/sec: 1049.52
I1120 13:40:33.829339 140684764419520 tpu_estimator.py:2308] examples/sec: 1049.52
INFO:tensorflow:Enqueue next (1000) batch(es) of data to infeed.
I1120 13:40:33.830607 140684764419520 tpu_estimator.py:600] Enqueue next (1000) batch(es) of data to infeed.
INFO:tensorflow:Dequeue next (1000) batch(es) of data from outfeed.
I1120 13:40:33.830862 140684764419520 tpu_estimator.py:604] Dequeue next (1000) batch(es) of data from outfeed.
INFO:tensorflow:Outfeed finished for iteration (7, 0)
I1120 13:40:34.267921 140681504278272 tpu_estimator.py:279] Outfeed finished for iteration (7, 0)
I1120 13:40:39.989195 140681495885568 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
W1120 13:40:40.056418 140681495885568 preempted_hook.py:91] TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
I1120 13:41:10.124164 140681495885568 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
W1120 13:41:10.177670 140681495885568 preempted_hook.py:91] TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
I1120 13:41:40.259634 140681495885568 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
W1120 13:41:40.309398 140681495885568 preempted_hook.py:91] TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
I1120 13:42:10.377460 140681495885568 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpuv3-5 in state READY, and health UNKNOWN.
W1120 13:42:10.431982 140681495885568 preempted_hook.py:91] TPUPollingThread found TPU tpuv3-5 in state READY, and health UNKNOWN.
I1120 13:42:40.508342 140681495885568 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
W1120 13:42:40.567739 140681495885568 preempted_hook.py:91] TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
I1120 13:43:10.638391 140681495885568 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
W1120 13:43:10.694900 140681495885568 preempted_hook.py:91] TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
I1120 13:43:40.763782 140681495885568 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
W1120 13:43:40.810777 140681495885568 preempted_hook.py:91] TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
I1120 13:44:10.889873 140681495885568 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
W1120 13:44:10.942733 140681495885568 preempted_hook.py:91] TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
I1120 13:44:41.011034 140681495885568 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
W1120 13:44:41.066553 140681495885568 preempted_hook.py:91] TPUPollingThread found TPU tpuv3-5 in state READY, and health HEALTHY.
```

Once this happens, I have to kill the process and restart training.

Note: Before I found this issue, I posted a question on StackOverflow: [TPU suddenly stops training](https://stackoverflow.com/questions/58917482/tpu-suddenly-stops-training).
The answer there (`rm -rf ~/.config/gcloud; gcloud components update`, giving TPU access to Cloud Bucket via IAM) doesn't claim to work all the time and indeed did not fix this issue for me.

**Comment by pwais** [comment]
+1 to @ChristopherBrix  I'd say 3hrs for me is the mean, but yes I have had several failures at the 30 minute mark.  

The only indication is the `and health UNKNOWN` message, as shown in your logs.  I'd love to automated restarting, but this log is very hard to get to.  The `tensorflow` client should probably disconnect / reconnect when it gets this error perhaps.

**Comment by michaelbanfield** [comment]
Hi Paul and Christopher,

The most common cause of this issue (TPU trains for sometime and then stalls/stops training) is the Tensorflow backend running out of host memory. 

The estimator framework attempts to restart training when this occurs however we've seen cases where this does not happen. Our plan for this is to exit the client code when the tensorflow backend exits (similar to what we do in https://github.com/tensorflow/tensorflow/blob/5fe944ad10a0913f7e3850a88216cd797479708e/tensorflow/python/tpu/preempted_hook.py )

Two things to try in the meantime.

1) Ensure the model is not using dataset.cache(), many models have a flag for this but it should be disabled when using TPU's, this reduces overall memory usage
2) Set this environment variable https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py#L581 , this splits the compilation and execution ops which makes the restart process more verbose.

**Comment by pwais** [comment]
Thanks @michaelbanfield !  

Sounds like this should include `UNKNOWN` rather than let the client spin indefinitely:
 * https://github.com/tensorflow/tensorflow/blob/5fe944ad10a0913f7e3850a88216cd797479708e/tensorflow/python/tpu/preempted_hook.py#L94 
and this should throw an exception so that user code can handle the outcome
 * https://github.com/tensorflow/tensorflow/blob/5fe944ad10a0913f7e3850a88216cd797479708e/tensorflow/python/tpu/preempted_hook.py#L101

In my code I use `repeat()`, `shuffle()`, and `prefetch()`, but no `cache()`.  I hope the extensive memory logs posted here as well as the other issue show that there is no user-discernible OOM.  Does stackdriver record an OOM like the linux kernel does?  I have not seen anything useful in stackdriver thus far.

**Comment by pwais** [comment]
@michaelbanfield I tried with `TPU_SPLIT_COMPILE_AND_EXECUTE=1` and I still see OOMs after a few hours.  The logging is slightly nicer (can see when compiling starts and ends), although now it's really apparent that compiling takes several minutes, even for FastRCNN (and longer for RetinaNet).

**Comment by josecannete** [comment]
Same problem here, any solution so far?

**Comment by shauheen** [comment]
Thanks @pwais @josecannete for reporting this. We are aware of this issue and actively looking into a fix. Sorry for the delay. We will update this issue once we have a fix.

**Comment by pwais** [comment]
I tried a code hack that makes the client throw when the TPU health goes bad.  @shauheen The problem (during my first test at least) is that the TPU continues to report as `HEALTHY` despite memory graphs clearly showing the contrary:
<img width="1193" alt="Screen Shot 2019-11-25 at 11 12 19" src="https://user-images.githubusercontent.com/218145/69570687-2552e000-0f75-11ea-9bb1-5fd1cc9ded9b.png">

So in that above screenshot, my client python program has been spinning for ~30 mins with the following API response:
```
{'acceleratorType': 'v3-8',
 'cidrBlock': 'xxxx/29',
 'createTime': '2019-11-05T09:33:57.691822828Z',
 'description': 'A Cloud TPU created with the ctpu tool.',
 'health': 'HEALTHY',
 'ipAddress': 'xxxx',
 'name': 'projects/xxxx/locations/us-central1-a/nodes/xxxx',
 'network': 'global/networks/default',
 'networkEndpoints': [{'ipAddress': 'xxxx', 'port': 8470}],
 'port': '8470',
 'schedulingConfig': {},
 'serviceAccount': 'xxxx@cloud-tpu.iam.gserviceaccount.com',
 'state': 'READY',
 'tensorflowVersion': '1.15'}
```

@shauheen please note that the "fix" pushed to Tensorflow 2.x will NOT actually help here because (1) it does not catch an unhealthy state and (2) well it appears that the API is telling lies anyways :P


Gonna test again, will report if it actually helps.  Here's the code hack:
```
class TPUBadHealth(Exception):
  pass
import threading
class FixedTPUPollingThread(threading.Thread):
  """Fix _TPUPollingThread to throw when the TPU API returns an invalid
  response; e.g. the program behind the TPU API has OOMed.
  
  Based upon a copy of _TPUPollingThread from Tensorflow r1.15.0
  """

  def __init__(self, cluster, session):
    import logging as _logging
    super(FixedTPUPollingThread, self).__init__()

    self.daemon = True
    self._running = True
    self._session_closed = False
    self._cluster = cluster
    self._session = session
    self._interval = 30

    # Some of the Google API libraries are quite chatty, so disable them.
    for name in ['googleapiclient.discovery', 'oauth2client.client']:
      _logging.getLogger(name).setLevel(_logging.WARNING)

  def run(self):
    import logging as _logging
    import threading
    import time

    from tensorflow.python.framework import errors
    from tensorflow.python.platform import tf_logging as logging
    while self._running:
      response = self._cluster._fetch_cloud_tpu_metadata()  # pylint: disable=protected-access
      logging.warning(
          'TPUPollingThread found TPU %s in state %s, and health %s.',
          self._cluster._tpu, response['state'],  # pylint: disable=protected-access
          response.get('health', 'UNKNOWN'))
      
      logging.info('patched response %s' % (response,))

      # NEW! Fix Google's poor OOM handling
      if response.get('health') != 'HEALTHY':
        raise TPUBadHealth(response)

      if 'state' in response and response['state'] in [
          'TERMINATED', 'PREEMPTED'
      ]:
        logging.warning('TPU node %s reached an unrecoverable state %s, '
                        'terminating the session now.', self._cluster._tpu,  # pylint: disable=protected-access
                        response['state'])
        # Try to close the session.
        self._session.close()
        time.sleep(self._interval)

        if not self._session_closed:
          # Raise an exception if the session.close() stucks.
          logging.warning('Cannot close session on TPU node %s.',
                          self._cluster._tpu)  # pylint: disable=protected-access

          raise errors.UnavailableError(
              None, None, 'TPU node %s reached an unrecoverable state %s.' %
              (self._cluster._tpu, response['state']))  # pylint: disable=protected-access

      time.sleep(self._interval)

from tensorflow.python.tpu import preempted_hook
preempted_hook._TPUPollingThread = FixedTPUPollingThread
```

**Comment by shauheen** [comment]
Thank you again @pwais for your great feedback and working with us on this issue. As recommended by @michaelbanfield can you please let us know if you have recreated the TPU. I don't think we are talking about the same fix as you have referred to in your previous comment.

**Comment by pwais** [comment]
Hi @shauheen , yes over the past 2-3 weeks I have repeatedly restarted as well as recreated reserved TPUv3s.  (Never preemptable ones).  

In my previous comment, I hope I show definitively that:
 1) The private GCloud TPU service appears to die as evidenced through memory graphs. 
 2) The open source TPU client does not receive a response indicating this failure, and thus the client (patched or unpatched) may spin indefinitely.  

Furthermore, I would add in previous comments I have remarked that stackdriver logs show nothing useful indicating why the TPU died.

@shauheen I see two major issues:
 1) The private GCloud TPU service is clearly not operating properly.  At the very least, it is incorrectly reporting that the TPU is in a healthy state.
 2) The private GCloud TPU service and open source client need to provide a much less opaque picture of TPU state such that end users can revise their code and/or mitigate failures.

**Comment by pwais** [comment]
@shauheen I just saw that perhaps a fix was pushed Google-side and that I should restart my TPUs.  Will do that and test again.

**Comment by pwais** [comment]
@shauheen  I deleted the TPUs and re-created ones (with the same names).  This process took quite a while, perhaps because of the underlying infrastructure.  I had previously been told that Google Cloud was using an outdated k8s cluster internally (e.g. AI Platform) for some products and thus deleting instances could take 10-15 minutes (and they were 1-2 quarters away from a fix).

In any case, I have so far observed 19 hours of uninterrupted service (with zero program changes on my end!), which is more uninterrupted hours of service than I've seen in well over a month.  @shauheen One other bug: the graphs below are from new TPUs instantiated around ~6pm, but I created them using the same names as the old ones.   So the charts are showing stats (for before 6pm) from TPUs that have technically now been deleted.  🤷‍♂ 
![Screen Shot 2019-11-26 at 13 05 36](https://user-images.githubusercontent.com/218145/69673037-44717080-104e-11ea-8f53-19ea21cb0b8f.png)
![Screen Shot 2019-11-26 at 13 05 04](https://user-images.githubusercontent.com/218145/69673040-44717080-104e-11ea-8c71-4677e42f9c91.png)

**Comment by shauheen** [comment]
Thank you @pwais for your patience with this issue as we have been working on fixing it. Please update the issue if your job did not succeed as expected and we will be happy to investigate further. For the other bug I would really appreciate if you would file a separate issue that we can track.

**Comment by nemotiger** [comment]
I also faced the same issue in the past few weeks, and that happens roughly 40% of the time. After restarting TPU, the problem still exist but rarely happened. In my case, this problem not only happened at training but also during evaluation and inference. Also, sometime the Tensorflow client will freeze when initializing TPU system.

**Comment by pwais** [comment]
@nemotiger did you stop-star the TPU or delete and re-create?  stop-start didn't help me, I had to re-create.

@shauheen Might you be able to briefly comment if the fix was pushed to all TPUs in all regions or just a subset?

**Comment by nemotiger** [comment]
@pwais After re-creating the TPU, there wasn't a single problem in 40 runs for me. Seems that all the issues are fixed now. Thanks for your answer.

**Comment by pwais** [comment]
🎉 yay!  yeah eval is also still broken for me, but I think it's a distinctly different issue, haven't pinned down yet.

**Comment by shauheen** [comment]
Thanks @pwais the fix was pushed to all TPUs. However as you mentioned the TPU needs to be recreated. This incident was in part related to [this issue](https://status.cloud.google.com/incident/container-engine/19012). We are working to ensure that these will have minimum impact on TPU users in the future.

**Comment by shauheen** [comment]
closing this issue as it seems to have been fixed, please feel free to reopen if the issue still persists.

**Comment by trieuduc** [comment]
I have this problem when trying to train deeplab model with this tutorial: https://cloud.google.com/tpu/docs/tutorials/deeplab. It happened right from the beginning. I tried to delete and re-create tpu few times but still not success.
```
Instructions for updating:
Prefer Variable.assign which has equivalent behavior in 2.X.
INFO:tensorflow:Initialized dataset iterators in 0 seconds
I0818 01:54:02.811702 140332374288128 util.py:98] Initialized dataset iterators in 0 seconds
INFO:tensorflow:Installing graceful shutdown hook.
I0818 01:54:02.812062 140332374288128 session_support.py:332] Installing graceful shutdown hook.
2020-08-18 01:54:02.812563: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:370] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
INFO:tensorflow:Creating heartbeat manager for ['/job:worker/replica:0/task:0/device:CPU:0']
I0818 01:54:03.071223 140332374288128 session_support.py:82] Creating heartbeat manager for ['/job:worker/replica:0/task:0/device:CPU:0']
INFO:tensorflow:Configuring worker heartbeat: shutdown_mode: WAIT_FOR_COORDINATOR
I0818 01:54:03.073406 140332374288128 session_support.py:105] Configuring worker heartbeat: shutdown_mode: WAIT_FOR_COORDINATOR
INFO:tensorflow:Init TPU system
I0818 01:54:04.360910 140332374288128 tpu_estimator.py:567] Init TPU system
INFO:tensorflow:Initialized TPU in 29 seconds
I0818 01:54:33.616278 140332374288128 tpu_estimator.py:576] Initialized TPU in 29 seconds
INFO:tensorflow:Starting infeed thread controller.
I0818 01:54:38.857639 140326404531968 tpu_estimator.py:521] Starting infeed thread controller.
INFO:tensorflow:Starting outfeed thread controller.
I0818 01:54:38.857989 140326396139264 tpu_estimator.py:540] Starting outfeed thread controller.
I0818 01:54:38.926282 140326387746560 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU b'deeplab-tutorial' in state READY, and health HEALTHY.
W0818 01:54:39.005942 140326387746560 preempted_hook.py:91] TPUPollingThread found TPU b'deeplab-tutorial' in state READY, and health HEALTHY.
INFO:tensorflow:Enqueue next (2000) batch(es) of data to infeed.
I0818 01:54:45.609667 140332374288128 tpu_estimator.py:600] Enqueue next (2000) batch(es) of data to infeed.
INFO:tensorflow:Dequeue next (2000) batch(es) of data from outfeed.
I0818 01:54:45.610682 140332374288128 tpu_estimator.py:604] Dequeue next (2000) batch(es) of data from outfeed.
I0818 01:55:09.070737 140326387746560 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU b'deeplab-tutorial' in state READY, and health HEALTHY.
W0818 01:55:09.125552 140326387746560 preempted_hook.py:91] TPUPollingThread found TPU b'deeplab-tutorial' in state READY, and health HEALTHY.
I0818 01:55:39.204904 140326387746560 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU b'deeplab-tutorial' in state READY, and health HEALTHY.
W0818 01:55:39.279920 140326387746560 preempted_hook.py:91] TPUPollingThread found TPU b'deeplab-tutorial' in state READY, and health HEALTHY.
I0818 01:56:09.333890 140326387746560 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU b'deeplab-tutorial' in state READY, and health HEALTHY.
W0818 01:56:09.398659 140326387746560 preempted_hook.py:91] TPUPollingThread found TPU b'deeplab-tutorial' in state READY, and health HEALTHY.
I0818 01:56:39.472497 140326387746560 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU b'deeplab-tutorial' in state READY, and health HEALTHY.
W0818 01:56:39.553414 140326387746560 preempted_hook.py:91] TPUPollingThread found TPU b'deeplab-tutorial' in state READY, and health HEALTHY.
I0818 01:57:09.617135 140326387746560 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU b'deeplab-tutorial' in state READY, and health HEALTHY.
W0818 01:57:09.677484 140326387746560 preempted_hook.py:91] TPUPollingThread found TPU b'deeplab-tutorial' in state READY, and health HEALTHY.
```

**Comment by mrngbaeb** [comment]
I am actually experiencing this issue now, which is persistent even after I shut down and restart the TPUs...
