### ISSUE TITLE
Inference with Model-Zoo MRCNN-SpineNet model fails, layer name mismatch

### ISSUE THREAD

**Issue by nss-ys** [tensorflow/tpu#770]
Hi, 

I am following the instructions on [GETTING_STARTED.md](https://github.com/tensorflow/tpu/blob/master/models/official/detection/GETTING_STARTED.md) to run inference on images.

When I use MRCNN-SpineNet143 pretrained checkpoint (available on [Model Zoo](https://github.com/tensorflow/tpu/blob/master/models/official/detection/MODEL_ZOO.md)) to get predictions,
```
## Ran on Google Colaboratory. Cloned github.com/tensorflow/tpu on 2020-05-14.

## Checkpoint and config are downloaded from Model Zoo
%env CHECKPOINT_PATH=gs://project-name/path/to/detection_maskrcnn_spinenet-143/model.ckpt
%env CONFIG_PATH=gs://project-name/path/to/spinenet143_mrcnn.yaml
%env LABEL_MAP_FILE=/path/to/tpu/models/official/detection/datasets/coco_label_map.csv
%env IMAGE_FILE_PATTERN=gs://project-name/path/to/*.JPG
%env MODEL=mask_rcnn
%env IMAGE_SIZE=1280
%env OUTPUT_HTML=./test.html
!python /path/to/tpu/models/official/detection/inference.py \
  --model="${MODEL?}" \
  --image_size=${IMAGE_SIZE?} \
  --checkpoint_path="${CHECKPOINT_PATH?}" \
  --config_path="${CONFIG_PATH?}" \
  --label_map_file="${LABEL_MAP_FILE?}" \
  --image_file_pattern="${IMAGE_FILE_PATTERN?}" \
  --output_html="${OUTPUT_HTML?}" \
```

the script complains about mismatch between the model and checkpoint:
```
2020-05-14 07:08:51.619987: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key fast_rcnn_head/fc7/bias not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key fast_rcnn_head/fc7/bias not found in checkpoint
	 [[{{node save/RestoreV2}}]]
  (1) Not found: Key fast_rcnn_head/fc7/bias not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_301]]
0 successful operations.
0 derived errors ignored.
```

Inspecting the ckpt, I noticed that layers with fast_rcnn_head/fc7 prefix are indeed missing (although we have fast_rcnn_head/fc6 layers):
```
!python tensorflow/tensorflow/python/tools/inspect_checkpoint.py \
--file_name=gs://project-name/path/to/detection_maskrcnn_spinenet-143/model.ckpt

...
fast_rcnn_head/conv_3/kernel/Momentum (DT_FLOAT) [3,3,256,256]
fast_rcnn_head/fc6/bias (DT_FLOAT) [1024]
fast_rcnn_head/fc6/bias/Momentum (DT_FLOAT) [1024]
fast_rcnn_head/fc6/kernel (DT_FLOAT) [12544,1024]
fast_rcnn_head/fc6/kernel/Momentum (DT_FLOAT) [12544,1024]
global_step (DT_INT64) []
...
```
... but not sure how to fix that. 
Is there a way to use the pretrained checkpoint for inference, or am I missing something?

**Comment by pengchongjin** [comment]
Hi,

It looks like your config file is not passed correctly. The following command worked for me.

(I noticed that you misspelled the flag `--config_file` with `--config_path`.)

```
CHECKPOINT_PATH="model.ckpt-164150"
CONFIG_PATH="spinenet143_mrcnn.yaml"
LABEL_MAP_FILE="coco_label_map.csv
IMAGE_FILE_PATTERN="./dog.jpg"
MODEL="mask_rcnn"
IMAGE_SIZE=1280
OUTPUT_HTML="./test.html"
python /path/to/tpu/models/official/detection/inference.py \
  --model="${MODEL?}" \
  --image_size=${IMAGE_SIZE?} \
  --checkpoint_path="${CHECKPOINT_PATH?}" \
  --config_file="${CONFIG_PATH?}" \
  --label_map_file="${LABEL_MAP_FILE?}" \
  --image_file_pattern="${IMAGE_FILE_PATTERN?}" \
  --output_html="${OUTPUT_HTML?}" \
```

**Comment by nss-ys** [comment]
Looks like that was a issue on my side!

Although fixing the typo causes a different type of error (see below), @apls777 has raised a issue already (#775).
Closing this thread as the original issue is solved. Thanks, @pengchongjin!

```
## Fixed typo.
python /path/to/tpu/models/official/detection/inference.py \
  --model="${MODEL?}" \
  --image_size=${IMAGE_SIZE?} \
  --checkpoint_path="${CHECKPOINT_PATH?}" \
  --config_file="${CONFIG_PATH?}" \
  --label_map_file="${LABEL_MAP_FILE?}" \
  --image_file_pattern="${IMAGE_FILE_PATTERN?}" \
  --output_html="${OUTPUT_HTML?}" \
```
```
I0518 03:20:00.575599 139856024643456 saver.py:1293] Restoring parameters from gs://iaffam/script/pretrained/detection_maskrcnn_spinenet-143/model.ckpt
2020-05-18 03:20:29.422902: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Out of range: EOF reached. Requested to read 2359296 bytes from 534587792 but only got 2283121 bytes.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: EOF reached. Requested to read 2359296 bytes from 534587792 but only got 2283121 bytes.
	 [[{{node save/RestoreV2}}]]
  (1) Out of range: EOF reached. Requested to read 2359296 bytes from 534587792 but only got 2283121 bytes.
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_301]]
0 successful operations.
0 derived errors ignored.
```

**Comment by raj-shah** [comment]
@nss-ys I'm still seeing a broken checkpoint wrt spinenet-190 in #913, any chance you could confirm this still works?

**Comment by raj-shah** [comment]
@nss-ys I'm still seeing a broken checkpoint wrt spinenet-190 in #913, does this still work for you?

**Comment by raj-shah** [comment]
@nss-ys I'm seeing a broken checkpoint wrt spinenet-190 in #913, does this still work for you?
